# Generated by Django 2.2.6 on 2019-10-26 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Строка данных',
                'verbose_name_plural': 'Строки данных',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='LocalizedString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default='')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization_app.DataString')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization_app.Language')),
            ],
            options={
                'verbose_name': 'Локализованная строка',
                'verbose_name_plural': 'Локализованные строки',
            },
        ),
    ]
